USE [master]
GO

/****** Object:  Database [Sandbox]    Script Date: 06/04/2019 8:46:20 AM ******/
DROP DATABASE IF EXISTS [Sandbox]
GO

/****** Object:  Database [Sandbox]    Script Date: 06/04/2019 8:46:20 AM ******/
CREATE DATABASE [Sandbox]
GO

ALTER DATABASE [Sandbox] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
    begin
        EXEC [Sandbox].[dbo].[sp_fulltext_database] @action = 'disable'
    end
GO

ALTER DATABASE [Sandbox] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [Sandbox] SET ANSI_NULLS OFF
GO

ALTER DATABASE [Sandbox] SET ANSI_PADDING OFF
GO

ALTER DATABASE [Sandbox] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [Sandbox] SET ARITHABORT OFF
GO

ALTER DATABASE [Sandbox] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [Sandbox] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [Sandbox] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [Sandbox] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [Sandbox] SET CURSOR_DEFAULT GLOBAL
GO

ALTER DATABASE [Sandbox] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [Sandbox] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [Sandbox] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [Sandbox] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [Sandbox] SET DISABLE_BROKER
GO

ALTER DATABASE [Sandbox] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [Sandbox] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [Sandbox] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [Sandbox] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [Sandbox] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [Sandbox] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [Sandbox] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [Sandbox] SET RECOVERY FULL
GO

ALTER DATABASE [Sandbox] SET MULTI_USER
GO

ALTER DATABASE [Sandbox] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [Sandbox] SET DB_CHAINING OFF
GO

ALTER DATABASE [Sandbox] SET FILESTREAM ( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [Sandbox] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [Sandbox] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [Sandbox] SET QUERY_STORE = OFF
GO